// Configuration: one JSON file, hot-reloaded on mtime change.
// Home directory layout (default ~/.clauderipple):
//   config.json   this file
//   ca.pem ca.key leaf.pem leaf.key   generated by the installer
//   logs/router.log (+ rotated .1 .2 ...)

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { CompatibleCaps } from "./compat.ts";

export type ProviderModel = {
  id: string;
  name?: string;
  /** Explicit per-model reasoning-effort support. An empty array disables the provider fallback. */
  effortLevels?: string[];
  /** The model's context window, as the vendor's `/models` reported it (`context_length`). */
  contextWindow?: number;
  /**
   * The protocol this model speaks, when it is not the provider's own.
   *
   * One subscription can serve several on one key and one catalog: OpenCode Go answers Responses,
   * Chat Completions and Anthropic Messages models on the same plan, and its `/models` lists them
   * all together (measured 2026-09-18). `wire` used to sit only on the provider, so that one
   * account had to be configured as three providers — a split the user saw, did not ask for, and
   * had to repeat in every `direct` rule. It belongs to the model, which is what actually varies.
   */
  wire?: "chat" | "responses" | "anthropic";
  /** This model's endpoint base, when its wire is served on another path than the provider's. */
  url?: string;
  /**
   * The auth convention this model's wire expects, when it differs from the provider's. The
   * provider's own key is re-sent under this header rather than restated here, so the key stays in
   * exactly one place.
   *
   * Each endpoint follows the convention of the API it imitates: an Anthropic-wire one wants
   * `x-api-key` while an OpenAI-wire one on the same key wants a bearer. Measured 2026-09-18 with a
   * deliberately wrong key — the header an endpoint does not recognise answers "Missing API key",
   * the one it does answers "Invalid API key".
   */
  authHeader?: "x-api-key" | "authorization-bearer";
};

/**
 * One credential in a provider's pool. `id` is what the router's health state is keyed on, so it
 * has to stay put across config edits — renaming one resets its cooldown. Never logged.
 */
export type ProviderCredential = {
  id: string;
  headers: Record<string, string>;
  /** Shown in the dashboard instead of the id. Not a secret, so keep the key out of it. */
  label?: string;
};

export type AnthropicCompatibleProvider = {
  /** An HTTP(S) endpoint that speaks Anthropic Messages (DeepSeek, Kimi, GLM, MiniMax, proxenos, ...). */
  type: "anthropic-compatible";
  /** e.g. "http://127.0.0.1:8787" or "https://api.deepseek.com/anthropic" */
  url: string;
  /** Optional headers to set on forwarded requests (e.g. x-api-key). Never logged. */
  headers?: Record<string, string>;
  /**
   * A header this vendor recognises a conversation by, filled with a value that is stable for one
   * conversation and different between two. Vendors that key their prompt cache on it charge full
   * price to anyone who omits it. Absent, nothing extra is sent.
   */
  sessionHeader?: string;
  /**
   * Further credentials for the same provider, tried when `headers` is rate limited or rejected.
   * Each is a complete header set, so vendors that need more than a key still work. A conversation
   * keeps whichever one it is on while that one is healthy, because moving it moves the prompt
   * cache with it. Absent, the provider has exactly the one credential it always had.
   */
  credentials?: ProviderCredential[];
  /** Catalog preset used to populate this provider, if any. */
  preset?: string;
  /** Optional model entries offered by the GUI as suggestions. */
  models?: ProviderModel[];
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Compatibility overrides. Unspecified fields fall back to the preset, then strict defaults. */
  caps?: CompatibleCaps;
};

export type ChatGptProvider = {
  /** Your ChatGPT subscription through the Codex backend; Anthropic Messages translated to OpenAI Responses. */
  type: "chatgpt";
  /** "borrow-codex" reads ~/.codex/auth.json (never refreshed by us); "own" uses `clauderipple login` tokens. Default: own if present, else borrow. */
  auth?: "own" | "borrow-codex" | "auto";
  /** Override the backend origin (default https://chatgpt.com/backend-api). */
  url?: string;
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Troubleshooting: true = dump failed upstream exchanges to <home>/debug/; "all" = dump every exchange (last 60). */
  debugDump?: boolean | "all";
  /** Reasoning effort when the request carries none. Default "high". */
  defaultEffort?: string;
  /** Optional processing tier for subscription Responses requests. */
  serviceTier?: "default" | "fast" | "priority";
  /** Models offered in the GUI (the Codex backend has no listing endpoint). */
  models?: ProviderModel[];
};

export type OpenAiCompatibleProvider = {
  /** An OpenAI-compatible API base, e.g. https://api.x.ai/v1. */
  type: "openai-compatible";
  url: string;
  /** Optional vendor headers, normally authorization: Bearer <key>. Never logged. */
  headers?: Record<string, string>;
  /**
   * A header this vendor uses to recognise a conversation, filled with a value that is stable for
   * one conversation and different between two (`x-opencode-session`, for instance). Vendors that
   * key their prompt cache on it hand a cold cache to anyone who does not send one, which costs
   * several times the tokens. Absent, nothing extra is sent.
   */
  sessionHeader?: string;
  /** OpenAI Chat Completions (default) or stateless Responses endpoint. */
  wire?: "chat" | "responses";
  /** Catalog preset used to populate this provider, if any. */
  preset?: string;
  /** Optional model entries offered by the GUI as suggestions. */
  models?: ProviderModel[];
  /** Prefix the system prompt with a one-line identity so the model knows what it is. Default true. */
  identity?: boolean;
  /** Fixed text appended to the system prompt. Must stay constant across turns or the prompt cache breaks. */
  instructionsAppend?: string;
  /** Reasoning-effort capability exposed by this API/model family. */
  caps?: { effortLevels?: string[]; reasoning?: "effort" | "none" };
};

export type AnthropicProvider = {
  /** Native Anthropic Messages API. */
  type: "anthropic";
  /** Console API key, or Claude Code/ClaudeRipple OAuth accounts. */
  auth: "api-key" | "claude-code";
  /** Required for api-key unless ANTHROPIC_API_KEY is set. Never logged. */
  apiKey?: string;
  /**
   * Route Claude app/CLI Messages calls through the Claude OAuth account pool. Opt-in so existing
   * native providers remain OpenAI-ingress-only and never start intercepting Claude traffic.
   */
  accountPool?: boolean;
  models?: ProviderModel[];
};

export type Provider = AnthropicCompatibleProvider | ChatGptProvider | OpenAiCompatibleProvider | AnthropicProvider;

/**
 * The provider's own key, re-sent under the header another wire on the same account expects.
 *
 * The key is never restated in a model entry, so there is exactly one copy of it to rotate and one
 * to leak. Every other header the provider set is kept: only the auth one is replaced, because
 * sending both conventions at once would hand the endpoint a credential it did not ask for.
 */
function reauthorized(headers: Record<string, string> | undefined, kind: "x-api-key" | "authorization-bearer"): Record<string, string> | undefined {
  if (!headers) return headers;
  const kept: Record<string, string> = {};
  let key: string | undefined;
  for (const [name, value] of Object.entries(headers)) {
    const lower = name.toLowerCase();
    if (lower === "x-api-key") { key ??= value; continue; }
    if (lower === "authorization") { key ??= value.replace(/^Bearer\s+/i, ""); continue; }
    kept[name] = value;
  }
  // Nothing recognisable to move: leave the headers exactly as they were rather than inventing an
  // empty credential, which would read to the endpoint as a missing key instead of a config error.
  if (key === undefined) return headers;
  if (kind === "x-api-key") kept["x-api-key"] = key;
  else kept.authorization = `Bearer ${key}`;
  return kept;
}

/**
 * The provider shape a request for `model` is actually talking to.
 *
 * A model may speak another wire than the rest of its provider, on another path, under another auth
 * convention (see `ProviderModel.wire`). Those overrides are folded back into an ordinary provider
 * here, so every `provider.type` branch downstream keeps working against one unchanged contract —
 * and one subscription stays one provider instead of three (2026-09-22).
 *
 * A provider with no override for this model is returned as it is, by identity, so nothing on the
 * ordinary path pays for this.
 */
export function providerFor(provider: Provider, model: string | undefined): Provider {
  if (!model || !("models" in provider) || !provider.models) return provider;
  const entry = provider.models.find((m) => m.id === model);
  if (!entry || (entry.wire === undefined && entry.url === undefined && entry.authHeader === undefined)) return provider;

  const url = entry.url ?? ("url" in provider ? provider.url : undefined);
  const headers = entry.authHeader
    ? reauthorized("headers" in provider ? provider.headers : undefined, entry.authHeader)
    : ("headers" in provider ? provider.headers : undefined);
  const shared = {
    ...provider,
    ...(url !== undefined ? { url } : {}),
    ...(headers !== undefined ? { headers } : {}),
  };

  // Anthropic Messages needs no translation, so this model is served by the anthropic-compatible
  // adapter instead. The two `caps` shapes do not describe the same things, and only an effort
  // ladder carries over; the rest fall back to the strict defaults `resolveCompatibleCaps` applies,
  // which is what the separate provider did before this.
  if (entry.wire === "anthropic") {
    const { wire: _wire, caps: _caps, ...rest } = shared as OpenAiCompatibleProvider;
    return { ...rest, type: "anthropic-compatible", url: url ?? "", caps: { effortLevels: entry.effortLevels ?? [] } } as AnthropicCompatibleProvider;
  }
  return { ...shared, type: "openai-compatible", url: url ?? "", ...(entry.wire ? { wire: entry.wire } : {}) } as OpenAiCompatibleProvider;
}

export type Route = {
  provider: string;
  model: string;
  effort?: string;
  /** Context window for this slot, when the routed model's differs. Falls back to `cli.autoCompactWindow`. */
  contextWindow?: number;
  /**
   * Where the turn goes when this provider cannot answer it — rate limited, rejected, or down.
   * Tried in order, and only for failures another provider could plausibly answer: a bad request
   * is refused everywhere, so it is not retried. Failover ends at the first byte of the answer,
   * because replacing a half-sent stream produces two answers spliced together.
   */
  fallbacks?: { provider: string; model: string; effort?: string }[];
};

export type DirectRule = {
  /** A request whose model starts with this prefix is sent to `provider` with the model unchanged. */
  prefix: string;
  provider: string;
};

export type CliModel = {
  model: string;
  name: string;
  description?: string;
  /**
   * This model's own context window. Routed models do not share one — forcing a single value on a
   * 1M-window model and a 400K one either overflows the smaller or throws away most of the larger.
   * Falls back to `cli.autoCompactWindow`. This is the model's real window, not a compaction
   * threshold: Claude Code applies its own fraction (measured: a 200K window compacted at 151K).
   */
  contextWindow?: number;
};

export type Config = {
  listen: { host: string; port: number; /** OpenAI-compatible ingress port. Defaults to port + 2. */ openaiPort?: number };
  upstream: string;
  providers: Record<string, Provider>;
  /** Picker-slot alias → route. Keys are the model ids the app sends (e.g. "claude-opus-4-8"). */
  routes: Record<string, Route>;
  /** Opt-in target for Claude Code's Auto mode security-monitor requests only. */
  autoModeClassifier?: Pick<Route, "provider" | "model" | "effort">;
  direct: DirectRule[];
  /** Short names usable in "[[ripple: sol@xhigh]]" markers and "@effort" suffixes. */
  aliases: Record<string, string>;
  effortClamp: Record<string, string>;
  cli: {
    /** Extra entries for the CLI's own /model picker (not the app picker; see docs/ARCHITECTURE.md §3). */
    extraModels: CliModel[];
    /** Fallback context window for routed models that do not declare their own (auto_compact_windows). */
    autoCompactWindow?: number;
    /**
     * Generate `~/.claude/agents/*.md` for the models config declares, so an agent file and the
     * alias a `[[ripple: xxx@effort]]` marker resolves to both come from one place. Only files this
     * router wrote (recorded in `generated-agents.json`) are touched. Default true.
     */
    agentFiles?: boolean;
    /**
     * Give generated workers only the tools a worker uses (read, edit, run, search, skills) instead of
     * every tool the session has. Each MCP server and plugin otherwise rides along on every worker
     * request (agents.ts). Such a worker cannot drive a browser or a simulator. Default false.
     */
    limitWorkerTools?: boolean;
    /**
     * Which model fills each of Claude Code's own slots, written into `~/.claude/settings.json`
     * env. Claude Code decides these before a request exists, so the router cannot reach them by
     * routing: a search, a session title or a subagent goes wherever the CLI already decided.
     *
     * `smallFast` is the one that matters most. Claude Code runs `WebSearch` as a side request
     * against it, so left at its default a routed session still searches on Claude quota — and a
     * user without a Claude subscription cannot search at all. Pointed at a routed model, the
     * provider does its own search and pays for it (§4).
     *
     * Each is left alone when unset, so nothing here changes behaviour until it is chosen.
     */
    models?: {
      /** ANTHROPIC_MODEL — the session default. */
      main?: string;
      /** ANTHROPIC_SMALL_FAST_MODEL — web search, titles, classifiers. */
      smallFast?: string;
      /** CLAUDE_CODE_SUBAGENT_MODEL — what a subagent runs on unless it names its own. */
      subagent?: string;
    };
  };
  /**
   * Who performs a `WebSearch`. Claude Code sends the search as its own side request to a small
   * model, so by default it costs Claude quota whatever the session is routed to — a routed setup
   * that still cannot search without a Claude subscription. Set this and the named provider's own
   * hosted search answers instead. Absent, nothing is intercepted and the search behaves as before.
   */
  webSearch?: {
    /** A key of `providers`, speaking an OpenAI-compatible Chat Completions API with a web plugin. */
    provider: string;
    /** The model that runs the search. Its hosted search does the work, so a small one is enough. */
    model: string;
    maxResults?: number;
  };
  health: {
    /** Consecutive upstream connect/DNS failures before the process exits for the supervisor to restart it. */
    maxConsecutiveUpstreamFailures: number;
  };
  log: {
    maxBytes: number;
    keep: number;
  };
  /** Local admin API + GUI. Binds 127.0.0.1 only. Defaults to listen.port + 1. */
  admin?: { port: number };
  /**
   * Picker mode: also terminate the app's own claude.ai traffic and add `cli.extraModels`
   * to the model picker. Needs the CA trusted in the login keychain and the app started
   * with our proxy (both done by `clauderipple picker on`).
   */
  picker?: { enabled: boolean; hosts?: string[] };
};

export const PICKER_HOSTS_DEFAULT = ["claude.ai"];

export function terminateHosts(c: Config): string[] {
  const hosts = [c.upstream];
  if (c.picker?.enabled) hosts.push(...(c.picker.hosts ?? PICKER_HOSTS_DEFAULT));
  return hosts;
}

export const DEFAULTS: Config = {
  listen: { host: "127.0.0.1", port: 8790 },
  upstream: "api.anthropic.com",
  providers: {},
  routes: {},
  direct: [],
  aliases: {},
  effortClamp: { ultra: "max" },
  cli: { extraModels: [], agentFiles: true },
  health: { maxConsecutiveUpstreamFailures: 20 },
  log: { maxBytes: 5 * 1024 * 1024, keep: 3 },
};

export function homeDir(): string {
  return process.env.CLAUDERIPPLE_HOME ?? path.join(os.homedir(), ".clauderipple");
}

export function configPath(): string {
  return path.join(homeDir(), "config.json");
}

function merge(base: Config, over: Partial<Config>): Config {
  return {
    ...base,
    ...over,
    listen: { ...base.listen, ...(over.listen ?? {}) },
    cli: { ...base.cli, ...(over.cli ?? {}) },
    health: { ...base.health, ...(over.health ?? {}) },
    log: { ...base.log, ...(over.log ?? {}) },
    effortClamp: { ...base.effortClamp, ...(over.effortClamp ?? {}) },
    ...((over.admin ?? base.admin) ? { admin: over.admin ?? base.admin! } : {}),
    ...(over.picker ? { picker: { ...over.picker } } : {}),
  };
}

/**
 * An HTTP header value is bytes, so anything above U+00FF cannot travel in one. A key pasted with
 * the label beside it — "API 키 sk-…" — fails deep inside the HTTP client with a message about
 * ByteString conversion and a character code, which tells the person nothing about what they did.
 * Returns what to say instead, or null when the value is fine.
 */
export function headerValueProblem(value: string): string | null {
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code > 0xff) return `character ${i + 1} is "${value[i]}", which cannot travel in an HTTP header — paste the key on its own, without any label or surrounding text`;
    // A newline would split the header; a stray one usually means a copied line rather than a key.
    if (code === 0x0a || code === 0x0d) return `there is a line break at character ${i + 1} — paste the key on its own, without the line around it`;
  }
  return null;
}

/** Named once because three provider kinds report it, and a drifting copy would describe the wrong shape. */
const MODELS_SHAPE = 'models must be entries with a string id and optional name, effortLevels, url, wire ("chat" | "responses" | "anthropic") and authHeader ("x-api-key" | "authorization-bearer")';

function validModels(models: unknown): boolean {
  return Array.isArray(models) && models.every((model) => {
    if (model === null || typeof model !== "object") return false;
    const m = model as ProviderModel;
    if (typeof m.id !== "string") return false;
    if (m.name !== undefined && typeof m.name !== "string") return false;
    if (m.effortLevels !== undefined && (!Array.isArray(m.effortLevels) || m.effortLevels.some((level) => typeof level !== "string"))) return false;
    // A model's own wire, endpoint and auth convention: wrong here and the request goes out in the
    // wrong shape to the wrong path, which reads as a provider that rejects a working key.
    if (m.wire !== undefined && m.wire !== "chat" && m.wire !== "responses" && m.wire !== "anthropic") return false;
    if (m.url !== undefined && (typeof m.url !== "string" || !/^https?:\/\//.test(m.url))) return false;
    if (m.authHeader !== undefined && m.authHeader !== "x-api-key" && m.authHeader !== "authorization-bearer") return false;
    return true;
  });
}

/**
 * The presets one OpenCode Go account had to be split across, and what each third actually was.
 *
 * Keyed on `preset` rather than on the provider's name: the GUI chose those names itself
 * (`opencode-go-responses`) and the user may have chosen others since.
 */
const SPLIT_BY_PRESET = {
  "opencode-go": { wire: "responses", authHeader: "authorization-bearer" },
  "opencode-go-chat": { wire: "chat", authHeader: "authorization-bearer" },
  "opencode-go-anthropic": { wire: "anthropic", authHeader: "x-api-key" },
} as const;

/** The effort ladder a provider actually offered, so it can travel with the models that had it. */
function ladderOf(p: Provider): string[] {
  if (p.type === "openai-compatible") return p.caps?.reasoning === "effort" ? [...(p.caps.effortLevels ?? [])] : [];
  if (p.type === "anthropic-compatible") return [...(p.caps?.effortLevels ?? [])];
  return [];
}

/**
 * The three providers one OpenCode Go account used to need, read as the single provider it is.
 *
 * `wire` and `url` sat on the provider, so an account whose models speak Responses, Chat
 * Completions and Anthropic Messages had to be configured three times — and every `direct` rule had
 * to name whichever third its model lived in. A model carries its own wire now, so a config written
 * against the old shape is folded here on the way in.
 *
 * Nothing is rewritten on disk. A save from the GUI is what eventually settles it, and until then
 * this stays reversible: the file still describes what an older router would read correctly.
 *
 * Every model keeps its own endpoint, wire and auth convention rather than inheriting the merged
 * provider's, so which third happens to become the base cannot change where a request goes.
 */
function foldSplitProviders(c: Config): Config {
  const parts = Object.entries(c.providers).filter(
    ([, p]) => "preset" in p && typeof p.preset === "string" && p.preset in SPLIT_BY_PRESET,
  );
  // One of them on its own is not a split, and is left exactly as it is.
  if (parts.length < 2) return c;

  const [baseName, baseProvider] = parts.find(([, p]) => (p as { preset?: string }).preset === "opencode-go") ?? parts[0]!;
  // Take the canonical name unless something outside the split already holds it.
  const name = parts.some(([n]) => n === "opencode-go") || !("opencode-go" in c.providers) ? "opencode-go" : baseName;

  const models: ProviderModel[] = [];
  for (const [, p] of parts) {
    const split = SPLIT_BY_PRESET[(p as { preset: keyof typeof SPLIT_BY_PRESET }).preset];
    const ladder = ladderOf(p);
    for (const model of ("models" in p && p.models) || []) {
      // `/models` lists every model on the plan, so the same id can appear under more than one
      // third. The first one wins: they describe one model, and a duplicate entry would shadow it.
      if (models.some((m) => m.id === model.id)) continue;
      models.push({
        ...model,
        wire: split.wire,
        authHeader: split.authHeader,
        ...("url" in p ? { url: p.url } : {}),
        // The merged provider's caps no longer describe this model, so the ladder its own endpoint
        // published travels with it. Inheriting the Responses one would start sending an effort to
        // an endpoint that never accepted one.
        effortLevels: model.effortLevels ?? ladder,
      });
    }
  }

  const providers: Config["providers"] = {};
  for (const [n, p] of Object.entries(c.providers)) if (!parts.some(([partName]) => partName === n)) providers[n] = p;
  providers[name] = { ...baseProvider, preset: "opencode-go", models } as Provider;

  // Every reference to a name that has just gone follows it, or the config stops validating on a
  // provider the user never removed.
  const moved = new Map(parts.map(([n]) => [n, name] as const).filter(([from, to]) => from !== to));
  const renamed = (of: string): string => moved.get(of) ?? of;
  return {
    ...c,
    providers,
    direct: c.direct.map((d) => ({ ...d, provider: renamed(d.provider) })),
    routes: Object.fromEntries(Object.entries(c.routes).map(([alias, r]) => [alias, {
      ...r,
      provider: renamed(r.provider),
      ...(r.fallbacks ? { fallbacks: r.fallbacks.map((f) => ({ ...f, provider: renamed(f.provider) })) } : {}),
    }])),
  };
}

export function validate(c: Config): string[] {
  const errors: string[] = [];
  if (c.autoModeClassifier !== undefined) {
    const target = c.autoModeClassifier;
    if (!target || typeof target !== "object") errors.push("autoModeClassifier must be an object");
    else {
      const provider = c.providers[target.provider];
      if (!provider) errors.push("autoModeClassifier: unknown provider");
      else if (provider.type === "anthropic" && !provider.accountPool) errors.push("autoModeClassifier: provider is ingress-only");
      if (typeof target.model !== "string" || !target.model.trim()) errors.push("autoModeClassifier: missing model");
      if (target.effort !== undefined && typeof target.effort !== "string") errors.push("autoModeClassifier: effort must be a string");
    }
  }
  for (const [alias, r] of Object.entries(c.routes)) {
    if (!c.providers[r.provider]) errors.push(`route ${alias}: unknown provider "${r.provider}"`);
    if (!r.model) errors.push(`route ${alias}: missing model`);
    // A fallback is only reached when something has already gone wrong, so a broken one is found
    // on the worst possible day. Refuse it at save time instead.
    if (r.fallbacks !== undefined) {
      if (!Array.isArray(r.fallbacks)) errors.push(`route ${alias}: fallbacks must be a list`);
      else r.fallbacks.forEach((f, i) => {
        if (!f || typeof f !== "object") { errors.push(`route ${alias}: fallback ${i} must be an object`); return; }
        if (!c.providers[f.provider]) errors.push(`route ${alias}: fallback ${i} names unknown provider "${f.provider}"`);
        // A native `anthropic` provider is routable only when its Claude OAuth pool is explicitly
        // enabled. Existing native providers remain ingress-only to avoid hijacking Claude traffic.
        else if (c.providers[f.provider]!.type === "anthropic" && !(c.providers[f.provider] as AnthropicProvider).accountPool) errors.push(`route ${alias}: fallback ${i} names "${f.provider}", which serves the OpenAI ingress only`);
        if (!f.model || typeof f.model !== "string") errors.push(`route ${alias}: fallback ${i} missing model`);
        if (f.provider === r.provider && f.model === r.model) errors.push(`route ${alias}: fallback ${i} repeats the primary target`);
      });
    }
  }
  for (const d of c.direct) {
    if (!c.providers[d.provider]) errors.push(`direct ${d.prefix}: unknown provider "${d.provider}"`);
  }
  for (const [name, p] of Object.entries(c.providers)) {
    // Carried by every provider that puts together a system prompt, so checked once for all of them.
    const shared = p as { identity?: unknown; instructionsAppend?: unknown };
    if (shared.identity !== undefined && typeof shared.identity !== "boolean") errors.push(`provider ${name}: identity must be true or false`);
    if (shared.instructionsAppend !== undefined && typeof shared.instructionsAppend !== "string") errors.push(`provider ${name}: instructionsAppend must be a string`);
    // Ids key the router's cooldown and quarantine state, so a duplicate would make two credentials
    // share one health record and take each other down.
    const pool = (p as { credentials?: unknown }).credentials;
    if (pool !== undefined) {
      if (!Array.isArray(pool)) errors.push(`provider ${name}: credentials must be a list`);
      else {
        const seen = new Set<string>();
        pool.forEach((entry, i) => {
          const cred = entry as { id?: unknown; headers?: unknown; label?: unknown } | null;
          if (!cred || typeof cred !== "object") { errors.push(`provider ${name}: credential ${i} must be an object`); return; }
          if (typeof cred.id !== "string" || !cred.id) errors.push(`provider ${name}: credential ${i} needs a non-empty id`);
          else if (seen.has(cred.id)) errors.push(`provider ${name}: credential id "${cred.id}" is used twice`);
          else seen.add(cred.id);
          if (!cred.headers || typeof cred.headers !== "object" || Array.isArray(cred.headers) ||
            Object.values(cred.headers as Record<string, unknown>).some((value) => typeof value !== "string")) {
            errors.push(`provider ${name}: credential ${i} headers must be a string record`);
          } else {
            for (const [header, value] of Object.entries(cred.headers as Record<string, string>)) {
              const problem = headerValueProblem(value);
              if (problem) errors.push(`provider ${name}: credential ${i} header "${header}": ${problem}`);
            }
          }
          if (cred.label !== undefined && typeof cred.label !== "string") errors.push(`provider ${name}: credential ${i} label must be a string`);
        });
      }
    }
    if (p.type === "anthropic-compatible") {
      if (!/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
      if (p.preset !== undefined && typeof p.preset !== "string") errors.push(`provider ${name}: preset must be a string`);
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: ${MODELS_SHAPE}`);
      }
      if (p.caps !== undefined) {
        const caps = p.caps;
        if (!caps || typeof caps !== "object" || Array.isArray(caps) ||
          (caps.effortLevels !== undefined && (!Array.isArray(caps.effortLevels) || caps.effortLevels.some((level) => typeof level !== "string"))) ||
          (caps.thinking !== undefined && caps.thinking !== "enabled" && caps.thinking !== "none") ||
          (caps.betas !== undefined && typeof caps.betas !== "boolean") ||
          (caps.cacheControl !== undefined && typeof caps.cacheControl !== "boolean")) {
          errors.push(`provider ${name}: caps must contain effortLevels?: string[], thinking?: "enabled"|"none", betas?: boolean, cacheControl?: boolean`);
        }
      }
    } else if (p.type === "chatgpt") {
      if (p.serviceTier !== undefined && p.serviceTier !== "default" && p.serviceTier !== "fast" && p.serviceTier !== "priority") errors.push(`provider ${name}: serviceTier must be "default", "fast", or "priority"`);
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: ${MODELS_SHAPE}`);
      }
      if (p.url && !/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
    } else if (p.type === "openai-compatible") {
      if (!/^https?:\/\//.test(p.url)) errors.push(`provider ${name}: url must start with http:// or https://`);
      if (p.wire !== undefined && p.wire !== "chat" && p.wire !== "responses") errors.push(`provider ${name}: wire must be "chat" or "responses"`);
      if (p.preset !== undefined && typeof p.preset !== "string") errors.push(`provider ${name}: preset must be a string`);
      if (p.headers !== undefined && (!p.headers || typeof p.headers !== "object" || Array.isArray(p.headers) || Object.values(p.headers).some((value) => typeof value !== "string"))) {
        errors.push(`provider ${name}: headers must be a string record`);
      }
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: ${MODELS_SHAPE}`);
      }
      if (p.caps !== undefined && (!p.caps || typeof p.caps !== "object" || Array.isArray(p.caps) ||
        (p.caps.effortLevels !== undefined && (!Array.isArray(p.caps.effortLevels) || p.caps.effortLevels.some((level) => typeof level !== "string"))) ||
        (p.caps.reasoning !== undefined && p.caps.reasoning !== "effort" && p.caps.reasoning !== "none"))) {
        errors.push(`provider ${name}: caps must contain effortLevels?: string[], reasoning?: "effort"|"none"`);
      }
    } else if (p.type === "anthropic") {
      if (p.auth !== "api-key" && p.auth !== "claude-code") errors.push(`provider ${name}: auth must be "api-key" or "claude-code"`);
      if (p.apiKey !== undefined && typeof p.apiKey !== "string") errors.push(`provider ${name}: apiKey must be a string`);
      if (p.accountPool !== undefined && typeof p.accountPool !== "boolean") errors.push(`provider ${name}: accountPool must be true or false`);
      if (p.accountPool && p.auth !== "claude-code") errors.push(`provider ${name}: accountPool requires auth "claude-code"`);
      if (p.models !== undefined && !validModels(p.models)) {
        errors.push(`provider ${name}: ${MODELS_SHAPE}`);
      }
    } else {
      errors.push(`provider ${name}: unknown type "${(p as { type?: string }).type}"`);
    }
  }
  if (!(c.listen.port > 0 && c.listen.port < 65536)) errors.push("listen.port out of range");
  if (c.cli.agentFiles !== undefined && typeof c.cli.agentFiles !== "boolean") errors.push("cli.agentFiles must be true or false");
  if (c.cli.limitWorkerTools !== undefined && typeof c.cli.limitWorkerTools !== "boolean") errors.push("cli.limitWorkerTools must be true or false");
  if (c.listen.openaiPort !== undefined && !(c.listen.openaiPort >= 0 && c.listen.openaiPort < 65536)) errors.push("listen.openaiPort out of range");
  return errors;
}

export class ConfigStore {
  private current: Config = DEFAULTS;
  private mtimeMs = -1;
  private readonly file: string;
  private readonly onChange: ((c: Config, errors: string[]) => void) | undefined;

  constructor(file = configPath(), onChange?: (c: Config, errors: string[]) => void) {
    this.file = file;
    this.onChange = onChange;
    this.reload(true);
  }

  /** Cheap: one stat per call. Called per request. */
  get(): Config {
    this.reload(false);
    return this.current;
  }

  private reload(initial: boolean): void {
    let st: fs.Stats;
    try {
      st = fs.statSync(this.file);
    } catch {
      if (initial) this.onChange?.(this.current, [`no config at ${this.file}; using defaults`]);
      this.mtimeMs = -1;
      return;
    }
    if (st.mtimeMs === this.mtimeMs) return;
    try {
      const parsed = JSON.parse(fs.readFileSync(this.file, "utf8")) as Partial<Config>;
      // Folded before validation, because the old three-provider shape is what is on disk and the
      // references it carries have to be the ones that get checked.
      const next = foldSplitProviders(merge(DEFAULTS, parsed));
      const errors = validate(next);
      if (errors.length === 0 || initial) this.current = next;
      this.mtimeMs = st.mtimeMs;
      this.onChange?.(this.current, errors);
    } catch (e) {
      this.mtimeMs = st.mtimeMs; // do not re-parse a broken file on every request
      this.onChange?.(this.current, [`config parse error: ${(e as Error).message}`]);
    }
  }
}
